language: android
# Enable container-based infrastructure
sudo: false
android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
branches:
  only:
    - master
before_install:
# Signature stub start
    - echo "stub keystore" > lbudget.keystore
    - echo "stub storage pwd" > lbudgetstorage.pwd
    - echo "stub key pwd" > lbudgetkey.pwd
# Signature stub end
    - chmod +x ./gradlew
script:
    - ./gradlew clean assembleStandardTravis
